{
  "version": "2.1.0",
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "runs": [
    {
      "tool": {
        "driver": {
          "fullName": "Docker Scout",
          "informationUri": "https://docker.com/products/docker-scout",
          "name": "docker scout",
          "rules": [
            {
              "id": "CVE-2024-0853",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "CVE-2024-0853"
              },
              "helpUri": "https://scout.docker.com/v/CVE-2024-0853?s=docker&n=curl&ns=alpine&t=apk&osn=alpine&osv=3.19&vr=%3C8.6.0-r0",
              "help": {
                "text": "\n",
                "markdown": "> \n\n|                |                                                             |\n|----------------|-------------------------------------------------------------|\n| Package        | pkg:apk/alpine/curl@8.5.0-r0?os_name=alpine&os_version=3.19 |\n| Affected range | <8.6.0-r0                                                   |\n| Fixed version  | not fixed                                                   |\n"
              },
              "properties": {
                "affected_version": "<8.6.0-r0",
                "cvssV3_severity": "MEDIUM",
                "fixed_version": "not fixed",
                "purls": [
                  "pkg:apk/alpine/curl@8.5.0-r0?os_name=alpine&os_version=3.19"
                ],
                "security-severity": "5.3",
                "tags": [
                  "MEDIUM"
                ]
              }
            },
            {
              "id": "CVE-2023-42364",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "CVE-2023-42364"
              },
              "helpUri": "https://scout.docker.com/v/CVE-2023-42364?s=alpine&n=busybox&ns=alpine&t=apk&osn=alpine&osv=3.19&vr=%3C1.36.1-r19",
              "help": {
                "text": "\n",
                "markdown": "> \n\n|                |                                                                  |\n|----------------|------------------------------------------------------------------|\n| Package        | pkg:apk/alpine/busybox@1.36.1-r18?os_name=alpine&os_version=3.19 |\n| Affected range | <1.36.1-r19                                                      |\n| Fixed version  | 1.36.1-r19                                                       |\n"
              },
              "properties": {
                "affected_version": "<1.36.1-r19",
                "cvssV3_severity": "MEDIUM",
                "fixed_version": "1.36.1-r19",
                "purls": [
                  "pkg:apk/alpine/busybox@1.36.1-r18?os_name=alpine&os_version=3.19"
                ],
                "security-severity": "5.5",
                "tags": [
                  "MEDIUM"
                ]
              }
            },
            {
              "id": "CVE-2023-42365",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "CVE-2023-42365"
              },
              "helpUri": "https://scout.docker.com/v/CVE-2023-42365?s=alpine&n=busybox&ns=alpine&t=apk&osn=alpine&osv=3.19&vr=%3C1.36.1-r19",
              "help": {
                "text": "\n",
                "markdown": "> \n\n|                |                                                                  |\n|----------------|------------------------------------------------------------------|\n| Package        | pkg:apk/alpine/busybox@1.36.1-r18?os_name=alpine&os_version=3.19 |\n| Affected range | <1.36.1-r19                                                      |\n| Fixed version  | 1.36.1-r19                                                       |\n"
              },
              "properties": {
                "affected_version": "<1.36.1-r19",
                "cvssV3_severity": "MEDIUM",
                "fixed_version": "1.36.1-r19",
                "purls": [
                  "pkg:apk/alpine/busybox@1.36.1-r18?os_name=alpine&os_version=3.19"
                ],
                "security-severity": "5.5",
                "tags": [
                  "MEDIUM"
                ]
              }
            },
            {
              "id": "CVE-2024-35195",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "CVE-2024-35195: Always-Incorrect Control Flow Implementation"
              },
              "helpUri": "https://scout.docker.com/v/CVE-2024-35195?s=github&n=requests&t=pypi&vr=%3C2.32.0",
              "help": {
                "text": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655\n",
                "markdown": "> When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655\n\n|                |                                              |\n|----------------|----------------------------------------------|\n| Package        | pkg:pypi/requests@2.31.0                     |\n| Affected range | <2.32.0                                      |\n| Fixed version  | 2.32.0                                       |\n| CVSS Score     |                                          5.6 |\n| CVSS Vector    | CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N |\n"
              },
              "properties": {
                "affected_version": "<2.32.0",
                "cvssV3": 5.6,
                "cvssV3_severity": "MEDIUM",
                "cvssV3_vector": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "fixed_version": "2.32.0",
                "purls": [
                  "pkg:pypi/requests@2.31.0"
                ],
                "security-severity": "5.6",
                "tags": [
                  "MEDIUM"
                ]
              }
            },
            {
              "id": "GHSA-c827-hfw6-qwvm",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "GHSA-c827-hfw6-qwvm"
              },
              "helpUri": "https://scout.docker.com/v/GHSA-c827-hfw6-qwvm?s=github&n=rustix&t=cargo&vr=%3E%3D0.37.0%2C%3C0.37.25",
              "help": {
                "text": "### Summary\n\nWhen using `rustix::fs::Dir` using the `linux_raw` backend, it's possible for the iterator to \"get stuck\" when an IO error is encountered. Combined with a memory over-allocation issue in `rustix::fs::Dir::read_more`, this can cause quick and unbounded memory explosion (gigabytes in a few seconds if used on a hot path) and eventually lead to an OOM crash of the application.\n\n### Details\n\n#### Discovery\n\nThe symptoms were initially discovered in https://github.com/imsnif/bandwhich/issues/284. That post has lots of details of our investigation. See [this post](https://github.com/imsnif/bandwhich/issues/284#issuecomment-1754321993) and the [Discord thread](https://discord.com/channels/273534239310479360/1161137828395237556) for details.\n\n#### Diagnosis\n\nThis issue is caused by the combination of two independent bugs:\n\n1. Stuck iterator\n- The `rustix::fs::Dir` iterator can fail to halt after encountering an IO error, causing the caller to be stuck in an infinite loop.\n2. Memory over-allocation\n- `Dir::read_more` incorrectly grows the read buffer unconditionally each time it is called, regardless of necessity.\n\nSince `<Dir as Iterator>::next` calls `Dir::read`, which in turn calls `Dir::read_more`, this means an IO error encountered during reading a directory can lead to rapid and unbounded growth of memory use.\n\n### PoC\n\n```rust\nfn main() -> Result<(), Box<dyn std::error::Error>> {\n    // create a directory, get a FD to it, then unlink the directory but keep the FD\n    std::fs::create_dir(\"tmp_dir\")?;\n    let dir_fd = rustix::fs::openat(\n        rustix::fs::CWD,\n        rustix::cstr!(\"tmp_dir\"),\n        rustix::fs::OFlags::RDONLY | rustix::fs::OFlags::CLOEXEC,\n        rustix::fs::Mode::empty(),\n    )?;\n    std::fs::remove_dir(\"tmp_dir\")?;\n\n    // iterator gets stuck in infinite loop and memory explodes\n    rustix::fs::Dir::read_from(dir_fd)?\n        // the iterator keeps returning `Some(Err(_))`, but never halts by returning `None`\n        // therefore if the implementation ignores the error (or otherwise continues\n        // after seeing the error instead of breaking), the loop will not halt\n        .filter_map(|dirent_maybe_error| dirent_maybe_error.ok())\n        .for_each(|dirent| {\n            // your happy path\n            println!(\"{dirent:?}\");\n        });\n\n    Ok(())\n}\n```\n\n### Impact\n\nIf a program tries to access a directory with its file descriptor after the file has been unlinked (or any other action that leaves the `Dir` iterator in the stuck state), and the implementation does not break after seeing an error, it can cause a memory explosion.\n\nAs an example, Linux's various virtual file systems (e.g. `/proc`, `/sys`) can contain directories that spontaneously pop in and out of existence. Attempting to iterate over them using `rustix::fs::Dir` directly or indirectly (e.g. with the `procfs` crate) can trigger this fault condition if the implementation decides to continue on errors.\n\nAn attacker knowledgeable about the implementation details of a vulnerable target can therefore try to trigger this fault condition via any one or a combination of several available APIs. If successful, the application host will quickly run out of memory, after which the application will likely be terminated by an OOM killer, leading to denial of service.\n",
                "markdown": "> ### Summary\n\nWhen using `rustix::fs::Dir` using the `linux_raw` backend, it's possible for the iterator to \"get stuck\" when an IO error is encountered. Combined with a memory over-allocation issue in `rustix::fs::Dir::read_more`, this can cause quick and unbounded memory explosion (gigabytes in a few seconds if used on a hot path) and eventually lead to an OOM crash of the application.\n\n### Details\n\n#### Discovery\n\nThe symptoms were initially discovered in https://github.com/imsnif/bandwhich/issues/284. That post has lots of details of our investigation. See [this post](https://github.com/imsnif/bandwhich/issues/284#issuecomment-1754321993) and the [Discord thread](https://discord.com/channels/273534239310479360/1161137828395237556) for details.\n\n#### Diagnosis\n\nThis issue is caused by the combination of two independent bugs:\n\n1. Stuck iterator\n- The `rustix::fs::Dir` iterator can fail to halt after encountering an IO error, causing the caller to be stuck in an infinite loop.\n2. Memory over-allocation\n- `Dir::read_more` incorrectly grows the read buffer unconditionally each time it is called, regardless of necessity.\n\nSince `<Dir as Iterator>::next` calls `Dir::read`, which in turn calls `Dir::read_more`, this means an IO error encountered during reading a directory can lead to rapid and unbounded growth of memory use.\n\n### PoC\n\n```rust\nfn main() -> Result<(), Box<dyn std::error::Error>> {\n    // create a directory, get a FD to it, then unlink the directory but keep the FD\n    std::fs::create_dir(\"tmp_dir\")?;\n    let dir_fd = rustix::fs::openat(\n        rustix::fs::CWD,\n        rustix::cstr!(\"tmp_dir\"),\n        rustix::fs::OFlags::RDONLY | rustix::fs::OFlags::CLOEXEC,\n        rustix::fs::Mode::empty(),\n    )?;\n    std::fs::remove_dir(\"tmp_dir\")?;\n\n    // iterator gets stuck in infinite loop and memory explodes\n    rustix::fs::Dir::read_from(dir_fd)?\n        // the iterator keeps returning `Some(Err(_))`, but never halts by returning `None`\n        // therefore if the implementation ignores the error (or otherwise continues\n        // after seeing the error instead of breaking), the loop will not halt\n        .filter_map(|dirent_maybe_error| dirent_maybe_error.ok())\n        .for_each(|dirent| {\n            // your happy path\n            println!(\"{dirent:?}\");\n        });\n\n    Ok(())\n}\n```\n\n### Impact\n\nIf a program tries to access a directory with its file descriptor after the file has been unlinked (or any other action that leaves the `Dir` iterator in the stuck state), and the implementation does not break after seeing an error, it can cause a memory explosion.\n\nAs an example, Linux's various virtual file systems (e.g. `/proc`, `/sys`) can contain directories that spontaneously pop in and out of existence. Attempting to iterate over them using `rustix::fs::Dir` directly or indirectly (e.g. with the `procfs` crate) can trigger this fault condition if the implementation decides to continue on errors.\n\nAn attacker knowledgeable about the implementation details of a vulnerable target can therefore try to trigger this fault condition via any one or a combination of several available APIs. If successful, the application host will quickly run out of memory, after which the application will likely be terminated by an OOM killer, leading to denial of service.\n\n|                |                                              |\n|----------------|----------------------------------------------|\n| Package        | pkg:cargo/rustix@0.37.19                     |\n| Affected range | >=0.37.0,<0.37.25                            |\n| Fixed version  | 0.37.25                                      |\n| CVSS Score     |                                          6.5 |\n| CVSS Vector    | CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H |\n"
              },
              "properties": {
                "affected_version": ">=0.37.0,<0.37.25",
                "cvssV3": 6.5,
                "cvssV3_severity": "MEDIUM",
                "cvssV3_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "fixed_version": "0.37.25",
                "purls": [
                  "pkg:cargo/rustix@0.37.19"
                ],
                "security-severity": "6.5",
                "tags": [
                  "MEDIUM"
                ]
              }
            }
          ],
          "version": "1.9.3"
        }
      },
      "results": [
        {
          "ruleId": "CVE-2024-0853",
          "ruleIndex": 0,
          "kind": "fail",
          "level": "warning",
          "message": {
            "text": "  Vulnerability   : CVE-2024-0853                                                \n  Severity        : MEDIUM                                                       \n  Package         : pkg:apk/alpine/curl@8.5.0-r0?os_name=alpine&os_version=3.19  \n  Affected range  : <8.6.0-r0                                                    \n  Fixed version   : not fixed                                                    \n  EPSS Score      : 0.000580                                                     \n  EPSS Percentile : 0.242120                                                     \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/lib/apk/db/installed"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/bin/curl"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/lib/libcurl.so.4.8.0"
                }
              }
            }
          ]
        },
        {
          "ruleId": "CVE-2023-42364",
          "ruleIndex": 1,
          "kind": "fail",
          "level": "warning",
          "message": {
            "text": "  Vulnerability   : CVE-2023-42364                                                    \n  Severity        : MEDIUM                                                            \n  Package         : pkg:apk/alpine/busybox@1.36.1-r18?os_name=alpine&os_version=3.19  \n  Affected range  : <1.36.1-r19                                                       \n  Fixed version   : 1.36.1-r19                                                        \n  EPSS Score      : 0.000440                                                          \n  EPSS Percentile : 0.127270                                                          \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/lib/apk/db/installed"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/securetty"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/udhcpc/udhcpc.conf"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/udhcpd.conf"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/share/udhcpc/default.script"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/bin/busybox"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/busybox-paths.d/busybox"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/logrotate.d/acpid"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/network/if-up.d/dad"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/bin/ssl_client"
                }
              }
            }
          ]
        },
        {
          "ruleId": "CVE-2023-42365",
          "ruleIndex": 2,
          "kind": "fail",
          "level": "warning",
          "message": {
            "text": "  Vulnerability   : CVE-2023-42365                                                    \n  Severity        : MEDIUM                                                            \n  Package         : pkg:apk/alpine/busybox@1.36.1-r18?os_name=alpine&os_version=3.19  \n  Affected range  : <1.36.1-r19                                                       \n  Fixed version   : 1.36.1-r19                                                        \n  EPSS Score      : 0.000440                                                          \n  EPSS Percentile : 0.127270                                                          \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/lib/apk/db/installed"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/securetty"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/udhcpc/udhcpc.conf"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/udhcpd.conf"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/share/udhcpc/default.script"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/bin/busybox"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/busybox-paths.d/busybox"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/logrotate.d/acpid"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/network/if-up.d/dad"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/bin/ssl_client"
                }
              }
            }
          ]
        },
        {
          "ruleId": "CVE-2024-35195",
          "ruleIndex": 3,
          "kind": "fail",
          "level": "warning",
          "message": {
            "text": "  Vulnerability   : CVE-2024-35195                                \n  Severity        : MEDIUM                                        \n  Package         : pkg:pypi/requests@2.31.0                      \n  Affected range  : <2.32.0                                       \n  Fixed version   : 2.32.0                                        \n  CVSS Score      : 5.6                                           \n  CVSS Vector     : CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N  \n  EPSS Score      : 0.000450                                      \n  EPSS Percentile : 0.154910                                      \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/lib/python3.11/site-packages/requests-2.31.0.dist-info/METADATA"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/lib/python3.11/site-packages/requests-2.31.0.dist-info/RECORD"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/lib/python3.11/site-packages/requests-2.31.0.dist-info/top_level.txt"
                }
              }
            }
          ]
        },
        {
          "ruleId": "GHSA-c827-hfw6-qwvm",
          "ruleIndex": 4,
          "kind": "fail",
          "level": "warning",
          "message": {
            "text": "  Vulnerability  : GHSA-c827-hfw6-qwvm                           \n  Severity       : MEDIUM                                        \n  Package        : pkg:cargo/rustix@0.37.19                      \n  Affected range : >=0.37.0,<0.37.25                             \n  Fixed version  : 0.37.25                                       \n  CVSS Score     : 6.5                                           \n  CVSS Vector    : CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H  \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/lib/librav1e.so.0.6.6"
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
